### ISSUE TITLE
Convert mentions to readable format for suggest command

### ISSUE THREAD

**Issue by cyrus01337** [DuckBot-Discord/DuckBot#36]
### Summary
When creating a suggestion that includes mentions, they appear in their raw form as per the nature of code-blocks in Discord. This will need to be copy/pasted so that those reading the suggestions can understand what is being referenced, this overhead sucks from a UX standpoint.

When making a suggestion:
![When making a suggestion](https://user-images.githubusercontent.com/63274991/221345316-74fc64c8-1714-4009-8452-58a5725df0dd.png)

When the suggestion is received:
![When the suggestion is received](https://user-images.githubusercontent.com/63274991/221345325-348dc323-9c44-403c-8d7a-16ada18f8cd0.png)

### Problem
Mentions of any kind appear in their raw form.

### Solution
Convert mentions found within the message to a readable format - there are various ways to retrieve this in Discord.py ([one](https://discordpy.readthedocs.io/en/latest/api.html?highlight=mentions#discord.Message.mentions), [two](https://discordpy.readthedocs.io/en/latest/api.html?highlight=mentions#discord.Message.channel_mentions), [three](https://discordpy.readthedocs.io/en/latest/api.html?highlight=mentions#discord.Message.role_mentions)) or they can be parsed manually should there be a need for it (I'm open to cobbling a pattern to handle such case[s]).

### Additional Info
I'm unsure if this was already patched in the rewrite or if this problem is actually an issue with the [hideout manager variant](https://github.com/DuckBot-Discord/duck-hideout-manager-bot).

**Comment by LeoCx1000** [comment]
This has been "fixed" in DuckBot-Discord/DuckBot@21d9ce3 (switched to a forum channel in the support server instead.)
